### PR TITLE
Update webpack to 4.29.6, CRA^3.0.1, craco^5.2.1

### LINKED ISSUE #11: Support for react-scripts ^3.0.0 (webpack 4.29.6)

### PR DESCRIPTION
**Pull request by swillis12**
This PR fixes #11. I've updated the tests, it looks like the default behavior is to have sourceMaps: true in craco. Let me know if there are any problems. Anyone feel free to edit/push more to this PR or suggest changes. I need these changes to update to CRA 3.0.1 in my project.

Thanks @ndbroadbent this project has been very useful to me.

### CODE REVIEW

**Comment by swillis12** [comment]
This looks like it's failing due to missing code coverage report. I did not make any changes related to this. Please advise if I need to push something to this PR to fix it.

**Comment by ndbroadbent** [comment]
@swillis12 Oh sorry, this is because I renamed my organization recently (FormAPI => DocSpring.) I will fix this in coveralls and re-run the build.

**Comment by miichu** [comment]
Any update on this? ✨

**Comment by ndbroadbent** [comment]
Sorry for the delay, this looks good! Will merge now!

**Comment by ndbroadbent** [comment]
Have published these changes in `1.8.0`. Thanks!

**Pull request merged**
