### PR TITLE
Bump dependencies versions to latest; Fixed potential webpack conflicts

### PR DESCRIPTION
**Pull request by alexandrtovmach**

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@ndbroadbent ping

**Comment by ndbroadbent** [comment]
Thanks @alexandrtovmach! Looks like the build just failed because of a 500 response from the coveralls API. So I'll merge it in!

**Comment by ndbroadbent** [comment]
Thanks again, I've pushed these changes in version `1.13.0`.

**Comment by alexandrtovmach** [comment]
@ndbroadbent okay, thank you

**Comment by ndbroadbent** [comment]
Hi, sorry I just remembered why I need to manually specify the webpack version. It's to avoid the warnings in the console whenever you install craco-less or craco-antd:

```
warning "craco-less > less-loader@5.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
```

It's just annoying to have this output in the console all the time, and it can be fixed by specifying the current webpack version from react-scripts as a peer dependency. I couldn't find any other way to silence this warning.

**Comment by alexandrtovmach** [comment]
@ndbroadbent okay, let me play with that. I'll try tomorrow to handle this conflicts

**Pull request merged**
