### PR TITLE
feat: support for CRA v5

### LINKED ISSUE #86: Can't find 'file-loader' issue with react-scripts 5.0.0
react-scripts version 5.0.0
@craco/craco version 6.4.3
craco-less version 1.20.0

```
/foobar/my-app/node_modules/@craco/craco/lib/plugin-utils.js:29
    throw new Error(
          ^

Error: Can't find file-loader in the development webpack config!

```

### PR DESCRIPTION
**Pull request by xyy94813**
Resolve #86

### CODE REVIEW

**Comment by csulit** [comment]
Waiting for this.

**Comment by xyy94813** [comment]
Do I need to consider compatibility with both v4 and v5?

Or, if someone is using the new version in CRA v4, do I need to give some feedback?

**Comment by ihoey** [comment]
Waiting for this.

**Comment by MyNameIsAlaa** [comment]
Waiting for this.

**Comment by tux-tn** [comment]
Will check it and try to merge it today. Sorry for the delay guys 🙏

**Comment by xyy94813** [comment]
It may not be necessary to use  `resolve-url-loader`
https://github.com/bholloway/resolve-url-loader/issues/200#issuecomment-999545339

**Review by tux-tn — APPROVED** [review]
LGTM 🎉  Thank you for your efforts @xyy94813

**Comment by tux-tn** [comment]
[craco-less@2.0.0](https://www.npmjs.com/package/craco-less) is out with support for CRA 5. Thank you guys and sorry for the delay

**Pull request merged**
